In [1]:
import pandas as pd
#---------------------------------------------------------------------------------------------------------------------------------------
cr286_vpins_2d_seismic_acq_lines = "../../data/Seis2D/cr286_vpins_2d_seismic_acq_lines.csv"
cr286_vpins_2d_seismic_acquisitions = "../../data/Seis2D/cr286_vpins_2d_seismic_acquisitions.csv"
cr286_vpins_2d_seismic_blocks = "../../data/Seis2D/cr286_vpins_2d_seismic_blocks.csv"
cr286_vpins_2d_seismic_contractors = "../../data/Seis2D/cr286_vpins_2d_seismic_contractors.csv"
cr286_vpins_2d_seismic_pro_lines = "../../data/Seis2D/cr286_vpins_2d_seismic_pro_lines.csv"
cr286_vpins_2d_seismic_pro_surveies = "../../data/Seis2D/cr286_vpins_2d_seismic_pro_surveies.csv"
cr286_vpins_2d_seismic_processings = "../../data/Seis2D/cr286_vpins_2d_seismic_processings.csv"
cr286_vpins_2d_seismic_shotpoints = "../../data/Seis2D/cr286_vpins_2d_seismic_shotpoints.csv"
cr286_vpins_2d_seismic_vessels = "../../data/Seis2D/cr286_vpins_2d_seismic_vessels.csv"
#---------------------------------------------------------------------------------------------------------------------------------------
acq_lines = pd.read_csv(cr286_vpins_2d_seismic_acq_lines)
acquisitions = pd.read_csv(cr286_vpins_2d_seismic_acquisitions)
blocks = pd.read_csv(cr286_vpins_2d_seismic_blocks)
contractors = pd.read_csv(cr286_vpins_2d_seismic_contractors)
pro_lines = pd.read_csv(cr286_vpins_2d_seismic_pro_lines)
pro_surveies = pd.read_csv(cr286_vpins_2d_seismic_pro_surveies)
processings = pd.read_csv(cr286_vpins_2d_seismic_processings)
shotpoints = pd.read_csv(cr286_vpins_2d_seismic_shotpoints)
vessels = pd.read_csv(cr286_vpins_2d_seismic_vessels)
#---------------------------------------------------------------------------------------------------------------------------------------
acq_lines = acq_lines[['cr286_line_id', 'cr286_line_length_km', 'cr286_line_name', 'cr286_seismic_2d_survey_id']]
acquisitions = acquisitions[['cr286_operator_id', 'cr286_seismic_2d_survey_id', 'cr286_seismic_2d_survey_name','cr286_total_length_km','cr286_cable_length_m',
                             'cr286_number_of_lines', 'cr286_fold_coverage_m','cr286_group_interval_m', 'cr286_record_length_ms','cr286_recording_format', 'cr286_sample_rate_ms',
                             'cr286_shotpoint_interval_m', 'cr286_source', 'cr286_source_depth_m','cr286_source_type', 'cr286_water_depth_from_m','cr286_water_depth_to_m', 'cr286_date_of_acquisition_commence','cr286_date_of_acquisition_completion']]
blocks = blocks[['cr286_block_id', 'cr286_record_id','cr286_seismic_2d_survey_id']]
contractors = contractors[['cr286_contractor_id', 'cr286_record_id', 'cr286_seismic_2d_survey_id']]
pro_lines = pro_lines[['cr286_line_id', 'cr286_record_id', 'cr286_seismic_2d_processing_id']]
pro_surveies = pro_surveies[['cr286_record_id', 'cr286_remarks', 'cr286_seismic_2d_processing_id', 'cr286_seismic_2d_survey_id']]
processings = processings[['cr286_contractor_id', 'cr286_date_of_processing_commence', 'cr286_date_of_processing_completion', 'cr286_number_of_lines', 'cr286_operator_id', 
                           'cr286_processing_result', 'cr286_processing_type', 'cr286_remarks', 'cr286_seismic_2d_processing_id', 'cr286_seismic_2d_processing_name', 'cr286_total_length_m']]
shotpoints = shotpoints[['cr286_line_id', 'cr286_shotpoint_id', 'cr286_shotpoint_name', 'cr286_latitude', 'cr286_longitude', 'cr286_crs_id']]
vessels =vessels[['cr286_record_id', 'cr286_seismic_2d_survey_id', 'cr286_vessel_id']]

#### 1. Seismic 2D LINES

In [2]:
acq_lines['cr286_line_length_km'] = acq_lines['cr286_line_length_km'].fillna(0)
print(acq_lines['cr286_line_id'].duplicated().any())
display(acq_lines.head(3))
cypher_seismic_line_txt = ""
for i in range(len(acq_lines)):
    _query = "MERGE (p:Seismic_2D_Line {{name: '{}', id: '{}', line_length: {}, survey: '{}'}})".format(
        acq_lines['cr286_line_name'][i], 
        acq_lines['cr286_line_id'][i], 
        acq_lines['cr286_line_length_km'][i], 
        acq_lines['cr286_seismic_2d_survey_id'][i], 
        )
    cypher_seismic_line_txt += _query + ';'
    if i < 3:
        print(_query)

False

,cr286_line_id,cr286_line_length_km,cr286_line_name,cr286_seismic_2d_survey_id
0,R001787,120.25,TC06-84-162,D2TCVM2
1,R001785,16.00,TC06-82A-165,D2TCVM2
2,R001786,94.53,TC06-83-163,D2TCVM2

MERGE (p:Seismic_2D_Line {name: 'TC06-84-162', id: 'R001787', line_length: 120.25, survey: 'D2TCVM2'})
MERGE (p:Seismic_2D_Line {name: 'TC06-82A-165', id: 'R001785', line_length: 16.0, survey: 'D2TCVM2'})
MERGE (p:Seismic_2D_Line {name: 'TC06-83-163', id: 'R001786', line_length: 94.53, survey: 'D2TCVM2'})

#### 2. Survey 2D

In [3]:
print(acquisitions['cr286_seismic_2d_survey_id'].duplicated().any())
display(acquisitions.head(3))

acquisitions['cr286_total_length_km'] = acquisitions['cr286_total_length_km'].fillna(0)
acquisitions['cr286_cable_length_m'] = acquisitions['cr286_cable_length_m'].fillna(0)
acquisitions['cr286_number_of_lines'] = acquisitions['cr286_number_of_lines'].fillna(0)
acquisitions['cr286_fold_coverage_m'] = acquisitions['cr286_fold_coverage_m'].fillna(0)
acquisitions['cr286_group_interval_m'] = acquisitions['cr286_group_interval_m'].fillna(0)
acquisitions['cr286_record_length_ms'] = acquisitions['cr286_record_length_ms'].fillna(0)
acquisitions['cr286_date_of_acquisition_commence'] = acquisitions['cr286_date_of_acquisition_commence'].apply(lambda x: x.replace(' 00:00:00.0000000', '') if type(x) == str else x)
acquisitions['cr286_date_of_acquisition_completion'] = acquisitions['cr286_date_of_acquisition_completion'].apply(lambda x: x.replace(' 00:00:00.0000000', '') if type(x) == str else x)

cypher_seismic_survey_txt = ""
for i in range(len(acquisitions)):
    _query = """MERGE (p:Seismic_2D_Survey {{name: '{}', id: '{}', survey_length: {}, cable_length: {}, operator_id: '{}', number_of_lines: {}, fold_coverage_m: {}, group_interval_m: {}, record_length_ms: {}, recording_format: '{}', sample_rate_ms: '{}', shotpoint_interval_m: '{}', source: '{}', source_depth_m: '{}', source_type: '{}', water_depth_from_m: '{}', water_depth_to_m: '{}', date_of_acquisition_commence: '{}', date_of_acquisition_completion: '{}'}})""".format(
        acquisitions['cr286_seismic_2d_survey_name'][i], 
        acquisitions['cr286_seismic_2d_survey_id'][i], 
        acquisitions['cr286_total_length_km'][i], 
        acquisitions['cr286_cable_length_m'][i], 
        acquisitions['cr286_operator_id'][i], 
        acquisitions['cr286_number_of_lines'][i], 
        acquisitions['cr286_fold_coverage_m'][i], 
        acquisitions['cr286_group_interval_m'][i], 
        acquisitions['cr286_record_length_ms'][i], 
        acquisitions['cr286_recording_format'][i], 
        acquisitions['cr286_sample_rate_ms'][i], 
        acquisitions['cr286_shotpoint_interval_m'][i], 
        acquisitions['cr286_source'][i], 
        acquisitions['cr286_source_depth_m'][i], 
        acquisitions['cr286_source_type'][i], 
        acquisitions['cr286_water_depth_from_m'][i], 
        acquisitions['cr286_water_depth_to_m'][i], 
        acquisitions['cr286_date_of_acquisition_commence'][i], 
        acquisitions['cr286_date_of_acquisition_completion'][i], 

        )
    cypher_seismic_survey_txt += _query + ';'
    if i < 3:
        print(_query)

False

,cr286_operator_id,cr286_seismic_2d_survey_id,cr286_seismic_2d_survey_name,cr286_total_length_km,cr286_cable_length_m,cr286_number_of_lines,cr286_fold_coverage_m,cr286_group_interval_m,cr286_record_length_ms,cr286_recording_format,cr286_sample_rate_ms,cr286_shotpoint_interval_m,cr286_source,cr286_source_depth_m,cr286_source_type,cr286_water_depth_from_m,cr286_water_depth_to_m,cr286_date_of_acquisition_commence,cr286_date_of_acquisition_completion
0,PVEP,D2TCVM2,PVEP06.TC.2D,19945.68,6000.0,224.0,120.0,12.5,8190.0,SEG-D,2.0,25.0,BCA010047,6.0,G-Gun Airgun array,NaN,NaN,2006-05-01 00:00:00.0000000,NaN
1,AEDC,D2NCS19,AEDC96.05-3.2D,NaN,NaN,NaN,NaN,25.0,6000.0,SEG-Y,2.0,25.0,BC_AEDC05.3_067,6.7,Airgun,NaN,NaN,1996-04-01 00:00:00.0000000,NaN
2,VSP,D2CL14,VSP96.09.2D,248.03,3000.0,26.0,60.0,12.5,5500.0,SEG-D,2.0,25.0,BCA001855,6.0,Airgun array,NaN,NaN,1996-05-01 00:00:00.0000000,1996-06-01 00:00:00.0000000

MERGE (p:Seismic_2D_Survey {name: 'PVEP06.TC.2D', id: 'D2TCVM2', survey_length: 19945.68, cable_length: 6000.0, operator_id: 'PVEP', number_of_lines: 224.0, fold_coverage_m: 120.0, group_interval_m: 12.5, record_length_ms: 8190.0, recording_format: 'SEG-D', sample_rate_ms: '2.0', shotpoint_interval_m: '25.0', source: 'BCA010047', source_depth_m: '6.0', source_type: 'G-Gun Airgun array', water_depth_from_m: 'nan', water_depth_to_m: 'nan', date_of_acquisition_commence: '2006-05-01', date_of_acquisition_completion: 'nan'})
MERGE (p:Seismic_2D_Survey {name: 'AEDC96.05-3.2D', id: 'D2NCS19', survey_length: 0.0, cable_length: 0.0, operator_id: 'AEDC', number_of_lines: 0.0, fold_coverage_m: 0.0, group_interval_m: 25.0, record_length_ms: 6000.0, recording_format: 'SEG-Y', sample_rate_ms: '2.0', shotpoint_interval_m: '25.0', source: 'BC_AEDC05.3_067', source_depth_m: '6.7', source_type: 'Airgun', water_depth_from_m: 'nan', water_depth_to_m: 'nan', date_of_acquisition_commence: '1996-04-01', date_of_acquisition_completion: 'nan'})
MERGE (p:Seismic_2D_Survey {name: 'VSP96.09.2D', id: 'D2CL14', survey_length: 248.03, cable_length: 3000.0, operator_id: 'VSP', number_of_lines: 26.0, fold_coverage_m: 60.0, group_interval_m: 12.5, record_length_ms: 5500.0, recording_format: 'SEG-D', sample_rate_ms: '2.0', shotpoint_interval_m: '25.0', source: 'BCA001855', source_depth_m: '6.0', source_type: 'Airgun array', water_depth_from_m: 'nan', water_depth_to_m: 'nan', date_of_acquisition_commence: '1996-05-01', date_of_acquisition_completion: '1996-06-01'})

#### 3. VESSELS

In [4]:
vessels = vessels[vessels['cr286_vessel_id'].notna()]
vessels = vessels.reset_index(drop=True)
vessels.head(3)
vessels_id = vessels['cr286_vessel_id'].unique()
cypher_vessel_txt = ""
for i in range(len(vessels_id)):
    _query = "MERGE (p:Vessel {{name: '{}', id: '{}'}})".format(vessels_id[i], 'VID_'+str(i+1))
    cypher_vessel_txt += _query + ';'
    if i < 3:
        print(_query)

MERGE (p:Vessel {name: 'SV_PROF_POLSHKOV', id: 'VID_1'})
MERGE (p:Vessel {name: 'MV_WESTERN_LEGEND', id: 'VID_2'})
MERGE (p:Vessel {name: 'RV_VERITAS_RESEARCHER', id: 'VID_3'})

### 4. Relationships

In [5]:
# Remove null values of cr286_block_id
blocks = blocks[blocks['cr286_block_id'].notna()]
blocks = blocks.reset_index(drop=True)
display(blocks.head(3))
cypher_bloc_survey_txt = ""
for i in range(len(blocks)):
    # WELL -> PROSPECT
    _query = """
    MATCH (s:Block {{id: '{}'}}), (o:Seismic_2D_Survey {{id: '{}'}})
    CREATE (s)-[:CÓ_KHẢO_SÁT {{record: '{}'}}]->(o)
    CREATE (o)-[:KHẢO_SÁT_TẠI {{record: '{}'}}]->(s)
    """.format(blocks['cr286_block_id'][i], 
                blocks['cr286_seismic_2d_survey_id'][i],
                blocks['cr286_record_id'][i],
                blocks['cr286_record_id'][i],
                )
    cypher_bloc_survey_txt += _query + ';'
print(_query)

  cr286_block_id cr286_record_id cr286_seismic_2d_survey_id
0           CL41         R000075                     D2CL14
1           MTC3         R000073                     D2MTC5
2           MTC4         R000074                     D2MTC5

    MATCH (s:Block {id: 'CL43'}), (o:Seismic_2D_Survey {id: 'D2CL1'})
    CREATE (s)-[:CÓ_KHẢO_SÁT {record: 'R000001'}]->(o)
    CREATE (o)-[:KHẢO_SÁT_TẠI {record: 'R000001'}]->(s)

In [6]:
print(acq_lines['cr286_line_id'].duplicated().any())
display(acq_lines.head(3))
cypher_line_survey_txt = ""
for i in range(len(acq_lines)):
    # WELL -> PROSPECT
    _query = """
    MATCH (s:Seismic_2D_Line {{id: '{}'}}), (o:Seismic_2D_Survey {{id: '{}'}})
    CREATE (s)-[:THUỘC_KHẢO_SÁT]->(o)
    CREATE (o)-[:CÓ_TUYẾN]->(s)
    """.format(acq_lines['cr286_line_id'][i], 
                acq_lines['cr286_seismic_2d_survey_id'][i],
                )
    cypher_line_survey_txt += _query + ';'
print(_query)

False

,cr286_line_id,cr286_line_length_km,cr286_line_name,cr286_seismic_2d_survey_id
0,R001787,120.25,TC06-84-162,D2TCVM2
1,R001785,16.00,TC06-82A-165,D2TCVM2
2,R001786,94.53,TC06-83-163,D2TCVM2

    MATCH (s:Seismic_2D_Line {id: 'R000003'}), (o:Seismic_2D_Survey {id: 'D2CL1'})
    CREATE (s)-[:THUỘC_KHẢO_SÁT]->(o)
    CREATE (o)-[:CÓ_TUYẾN]->(s)

In [7]:
vessels = vessels[vessels['cr286_vessel_id'].notna()]
vessels = vessels.reset_index(drop=True)
display(vessels.head(3))
cypher_vessel_survey_txt = ""
for i in range(len(vessels)):
    # WELL -> PROSPECT
    _query = """
    MATCH (s:Vessel {{name: '{}'}}), (o:Seismic_2D_Survey {{id: '{}'}})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)
    """.format(vessels['cr286_vessel_id'][i], 
                vessels['cr286_seismic_2d_survey_id'][i],
                )
    cypher_vessel_survey_txt += _query + ';'
print(_query)

  cr286_record_id cr286_seismic_2d_survey_id        cr286_vessel_id
0         R000057                    D2TCVM2       SV_PROF_POLSHKOV
1         R000056                     D2CL14      MV_WESTERN_LEGEND
2         R000054                    D2NCS20  RV_VERITAS_RESEARCHER

    MATCH (s:Vessel {name: 'LONGVA_II'}), (o:Seismic_2D_Survey {id: 'D2CL1'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

#### 5. Others

In [8]:
contractors = contractors[contractors['cr286_contractor_id'].notna()]
contractors = contractors.reset_index(drop=True)
contractors.head(3)

  cr286_contractor_id cr286_record_id cr286_seismic_2d_survey_id
0                SMNG         R000057                    D2TCVM2
1             DIGICON         R000053                    D2NCS19
2     PTSC_GEO_SUBSEA         R000055                     D2MTC5

In [9]:
processings['cr286_date_of_processing_commence'] = processings['cr286_date_of_processing_commence'].apply(lambda x: x.replace(' 00:00:00.0000000', '') if type(x) == str else x)
processings['cr286_date_of_processing_completion'] = processings['cr286_date_of_processing_completion'].apply(lambda x: x.replace(' 00:00:00.0000000', '') if type(x) == str else x)
processings.head(3)

,cr286_contractor_id,cr286_date_of_processing_commence,cr286_date_of_processing_completion,cr286_number_of_lines,cr286_operator_id,cr286_processing_result,cr286_processing_type,cr286_remarks,cr286_seismic_2d_processing_id,cr286_seismic_2d_processing_name,cr286_total_length_m
0,FAIRFIELD_VN,2006-10-07,2007-04-10,224.0,PVEP,NaN,NaN,Processing,P2TCVM2,PVEP06.TC.2D/PVEP06,19000.00
1,WESTERN_GEO,1996-07-08,1997-04-01,26.0,VSP,Final migration,NaN,Processing,P2CL13,VSP96.09.2D/VSP96,248.03
2,GOLDEN_PAC,NaN,NaN,24.0,IDEMITSU,PSTM,Time,Processing,P2NCS19,IDEMITSU05.05-1b&05-1c.2D/IDEMITSU05,500.00

### 6.Load to KG

In [16]:
import os
from neo4j import GraphDatabase
from dotenv import load_dotenv; load_dotenv()

LOCAL_NEO4J_URL=os.environ['NEO4J_URI']
LOCAL_NEO4J_USER=os.environ['NEO4J_USERNAME']
LOCAL_NEO4J_PASSWORD=os.environ['NEO4J_PASSWORD']

driver = GraphDatabase.driver(LOCAL_NEO4J_URL, auth=(LOCAL_NEO4J_USER, LOCAL_NEO4J_PASSWORD))
 
# _query = cypher_seismic_line_txt.split(';')
# _query = cypher_seismic_survey_txt.split(';')
# _query = cypher_vessel_txt.split(';')
# _query = cypher_bloc_survey_txt.split(';')
# _query = cypher_line_survey_txt.split(';')
_query = cypher_vessel_survey_txt.split(';')
for i, q in enumerate(_query[:-1]):
    print(i, '/', len(_query))
    print(q)
    driver.execute_query(q)

0 / 51

    MATCH (s:Vessel {name: 'SV_PROF_POLSHKOV'}), (o:Seismic_2D_Survey {id: 'D2TCVM2'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

1 / 51

    MATCH (s:Vessel {name: 'MV_WESTERN_LEGEND'}), (o:Seismic_2D_Survey {id: 'D2CL14'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

2 / 51

    MATCH (s:Vessel {name: 'RV_VERITAS_RESEARCHER'}), (o:Seismic_2D_Survey {id: 'D2NCS20'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

3 / 51

    MATCH (s:Vessel {name: 'PTSC_RESEARCHER'}), (o:Seismic_2D_Survey {id: 'D2MTC5'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

4 / 51

    MATCH (s:Vessel {name: 'MV_ROSS_SEAL'}), (o:Seismic_2D_Survey {id: 'D2NCS19'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

5 / 51

    MATCH (s:Vessel {name: 'SV_BINH_MINH_02'}), (o:Seismic_2D_Survey {id: 'D2PK8'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

6 / 51

    MATCH (s:Vessel {name: 'MV_ROSS_SEAL'}), (o:Seismic_2D_Survey {id: 'D2NCS17'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

7 / 51

    MATCH (s:Vessel {name: 'SV_STORMY'}), (o:Seismic_2D_Survey {id: 'D2NCS18'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

8 / 51

    MATCH (s:Vessel {name: 'SV_STORMY'}), (o:Seismic_2D_Survey {id: 'D2NCS16'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

9 / 51

    MATCH (s:Vessel {name: 'SV_ODYSSEE'}), (o:Seismic_2D_Survey {id: 'D2SH7'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

10 / 51

    MATCH (s:Vessel {name: 'CGG_DUKE'}), (o:Seismic_2D_Survey {id: 'D2SH8'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

11 / 51

    MATCH (s:Vessel {name: 'SV_ODYSSEE'}), (o:Seismic_2D_Survey {id: 'D2SH6'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

12 / 51

    MATCH (s:Vessel {name: 'ZEPHYR_1'}), (o:Seismic_2D_Survey {id: 'D2PK4'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

13 / 51

    MATCH (s:Vessel {name: 'ZEPHYR_1'}), (o:Seismic_2D_Survey {id: 'D2PK6'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

14 / 51

    MATCH (s:Vessel {name: 'ZEPHYR_1'}), (o:Seismic_2D_Survey {id: 'D2PK5'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

15 / 51

    MATCH (s:Vessel {name: 'RV_BINH_MINH_02'}), (o:Seismic_2D_Survey {id: 'D2MTC4'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

16 / 51

    MATCH (s:Vessel {name: 'AK_GAMBURTSEV'}), (o:Seismic_2D_Survey {id: 'D2PK3'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

17 / 51

    MATCH (s:Vessel {name: 'CGG_AMADEUS'}), (o:Seismic_2D_Survey {id: 'D2SH4'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

18 / 51

    MATCH (s:Vessel {name: 'SV_BINH_MINH_02'}), (o:Seismic_2D_Survey {id: 'D2SH5'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

19 / 51

    MATCH (s:Vessel {name: 'PROF_POLSHKOV'}), (o:Seismic_2D_Survey {id: 'D2CL13'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

20 / 51

    MATCH (s:Vessel {name: 'MV_POLSHKOV'}), (o:Seismic_2D_Survey {id: 'D2NCS14'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

21 / 51

    MATCH (s:Vessel {name: 'RV_VERITAS_RESEARCHER'}), (o:Seismic_2D_Survey {id: 'D2NCS13'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

22 / 51

    MATCH (s:Vessel {name: 'MV_GEO_EXP'}), (o:Seismic_2D_Survey {id: 'D2NCS15'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

23 / 51

    MATCH (s:Vessel {name: 'MV_ZEPHYR_I'}), (o:Seismic_2D_Survey {id: 'D2NCS12'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

24 / 51

    MATCH (s:Vessel {name: 'MN_WESTERN_HORIZON'}), (o:Seismic_2D_Survey {id: 'D2CL12'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

25 / 51

    MATCH (s:Vessel {name: 'RV_BINH_MINH_02'}), (o:Seismic_2D_Survey {id: 'D2SH3'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

26 / 51

    MATCH (s:Vessel {name: 'MV_STORMY'}), (o:Seismic_2D_Survey {id: 'D2CL11'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

27 / 51

    MATCH (s:Vessel {name: 'RV_BINH_MINH_02'}), (o:Seismic_2D_Survey {id: 'D2TCVM1'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

28 / 51

    MATCH (s:Vessel {name: 'MV_NAM_HAI_502'}), (o:Seismic_2D_Survey {id: 'D2CL10'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

29 / 51

    MATCH (s:Vessel {name: 'CGG_ZEPHYR'}), (o:Seismic_2D_Survey {id: 'D2NCS10'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

30 / 51

    MATCH (s:Vessel {name: 'SV_BINH_MINH_02'}), (o:Seismic_2D_Survey {id: 'D2PK2'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

31 / 51

    MATCH (s:Vessel {name: 'CGG_ZEPHYR'}), (o:Seismic_2D_Survey {id: 'D2NCS8'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

32 / 51

    MATCH (s:Vessel {name: 'GECO_MY'}), (o:Seismic_2D_Survey {id: 'D2MTC3'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

33 / 51

    MATCH (s:Vessel {name: 'GECO_KAPPA'}), (o:Seismic_2D_Survey {id: 'D2NCS9'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

34 / 51

    MATCH (s:Vessel {name: 'CGG_ZEPHYR'}), (o:Seismic_2D_Survey {id: 'D2NCS7'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

35 / 51

    MATCH (s:Vessel {name: 'AMARCO_TIGER'}), (o:Seismic_2D_Survey {id: 'D2MTC1'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

36 / 51

    MATCH (s:Vessel {name: 'AMARCO_TIGER'}), (o:Seismic_2D_Survey {id: 'D2MTC2'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

37 / 51

    MATCH (s:Vessel {name: 'BINH_MINH_02'}), (o:Seismic_2D_Survey {id: 'D2PK1'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

38 / 51

    MATCH (s:Vessel {name: 'SEA_CHALLENGER'}), (o:Seismic_2D_Survey {id: 'D2NCS3'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

39 / 51

    MATCH (s:Vessel {name: 'SEA_CHALLENGER'}), (o:Seismic_2D_Survey {id: 'D2NCS4'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

40 / 51

    MATCH (s:Vessel {name: 'PACIFIC_SWORD'}), (o:Seismic_2D_Survey {id: 'D2NCS6'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

41 / 51

    MATCH (s:Vessel {name: 'CGG_DUKE'}), (o:Seismic_2D_Survey {id: 'D2NCS5'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

42 / 51

    MATCH (s:Vessel {name: 'SEA_CHALLENGER'}), (o:Seismic_2D_Survey {id: 'D2CL9'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

43 / 51

    MATCH (s:Vessel {name: 'GECO_KAPPA'}), (o:Seismic_2D_Survey {id: 'D2SH1'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

44 / 51

    MATCH (s:Vessel {name: 'SEA_CHALLENGER'}), (o:Seismic_2D_Survey {id: 'D2CL8'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

45 / 51

    MATCH (s:Vessel {name: 'SEA_CHALLENGER'}), (o:Seismic_2D_Survey {id: 'D2NCS2'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

46 / 51

    MATCH (s:Vessel {name: 'LONGVA_II'}), (o:Seismic_2D_Survey {id: 'D2NCS1'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

47 / 51

    MATCH (s:Vessel {name: 'VERITAS_SEARCHER'}), (o:Seismic_2D_Survey {id: 'D2CL5'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

48 / 51

    MATCH (s:Vessel {name: 'BERGEN_SURVEYOR'}), (o:Seismic_2D_Survey {id: 'D2CL4'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)

49 / 51

    MATCH (s:Vessel {name: 'LONGVA_II'}), (o:Seismic_2D_Survey {id: 'D2CL1'})
    CREATE (s)-[:KHẢO_SÁT]->(o)
    CREATE (o)-[:SỬ_DỤNG]->(s)